### ISSUE TITLE
space between words in the file name gives error

### ISSUE THREAD

**Issue by masneg** [handiandi/fileJoker_downloader_cli#1]
Hi, thank you for this program.
The program gets error when the filename of  a filejoker like includes space.
the error happened in the part of file size of your program.

**Comment by handiandi** [comment]
Hi!
Oh ok. I will look into that, and return with a solution :)
Thank you!

**Comment by handiandi** [comment]
Hi again! 
I couldn't help to look at it right now, and I'm afraid that I need more information from you  :)

Is it when the file with links (using -f) contains spaces?
Or is it when it tries to find the size of file on the fileJoker website?
Can you copy paste the error massage? 

Thank you :)

**Comment by masneg** [comment]
Hi,
I am confused. before when I entered a link that the file name has webspace in the website page(for example: 	https://filejoker.net/h38ptrmkmwvr), i get the error.
now I do not get any error. 
the error happened in the line
result = [m.start() for m in re.finditer('<div class="name-size">', s)][0]
in geting the size of file on the website.
Thank you for your application.

**Comment by masneg** [comment]
before i get the error  in the line
`result = [m.start() for m in re.finditer('<div class="name-size">', s)][0]`
but now it works well, it's really strange.
I do not know what was the reason.
anyway, thank you a lot for this application.

**Comment by handiandi** [comment]
ok. Please write again if it happen several times in a row. If it does I have to solve it :P 
Glad you can use the application! 👍
